import type { Appearance } from "@clerk/types";

const fullWidth = "w-full max-w-full min-w-0 box-border";

/** Shared Clerk UI — matches Tradeverse dark theme (#141414 / #456DFF). */
export const clerkAuthAppearance: Appearance = {
  variables: {
    colorPrimary: "#456DFF",
    colorDanger: "#FF5D5D",
    colorSuccess: "#456DFF",
    colorWarning: "#F7C325",
    colorNeutral: "#999999",
    colorText: "#FFFFFF",
    colorTextSecondary: "#999999",
    colorBackground: "#1E1E1E",
    colorInputBackground: "#141414",
    colorInputText: "#FFFFFF",
    borderRadius: "0.75rem",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  elements: {
    rootBox: `${fullWidth} mx-auto`,
    cardBox: `${fullWidth} shadow-none`,
    card: `${fullWidth} bg-transparent shadow-none border-0 p-0 m-0 gap-6 overflow-hidden`,
    main: `${fullWidth} gap-6`,
    form: `${fullWidth} gap-4`,
    socialButtons: fullWidth,
    socialButtonsBlockButton: `${fullWidth} h-11 border border-white/10 bg-[#141414] text-white font-medium hover:bg-white/[0.06]`,
    socialButtonsBlockButtonText: "font-semibold text-white",
    dividerRow: fullWidth,
    dividerLine: "bg-white/10 flex-1",
    dividerText: "text-[#666] text-xs uppercase tracking-wider px-3",
    formField: fullWidth,
    formFieldRow: fullWidth,
    formFieldLabel: "text-sm font-medium text-[#ccc]",
    formFieldInput: `${fullWidth} h-11 border border-white/10 bg-[#141414] text-white placeholder:text-[#555]`,
    formButtonRow: fullWidth,
    formButtonPrimary: `${fullWidth} h-11 bg-[#456DFF] text-white font-bold hover:bg-[#2A4AE8]`,
    header: `${fullWidth} gap-2 text-left`,
    headerTitle: "text-xl font-black tracking-tight text-white sm:text-2xl",
    headerSubtitle: "text-sm text-[#999]",
    footer: `${fullWidth} bg-transparent pt-2`,
    footerPages: `${fullWidth} bg-transparent`,
    footerAction: `${fullWidth} justify-center`,
    footerActionText: "text-[#999]",
    footerActionLink: "text-[#88C9F7] font-semibold hover:text-[#456DFF]",
    identityPreview: fullWidth,
    identityPreviewText: "text-white font-medium",
    identityPreviewEditButton: "text-[#88C9F7]",
    formFieldAction: "text-[#88C9F7] font-medium hover:text-[#456DFF]",
    otpCodeFieldInput: `${fullWidth} border-white/10 bg-[#141414] text-white`,
    alert: fullWidth,
    alertText: "text-[#999]",
    formResendCodeLink: "text-[#88C9F7]",
    logoBox: "hidden",
    logoImage: "hidden",
    lastAuthenticationStrategyBadge: "text-xs",
  },
  layout: {
    socialButtonsPlacement: "top",
    socialButtonsVariant: "blockButton",
    logoPlacement: "none",
  },
};
